# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dummy_app.PingRequest" do
    optional :message, :string, 1
  end
  add_message "dummy_app.PingResult" do
    optional :message, :string, 1
  end
end

module DummyApp
  PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("dummy_app.PingRequest").msgclass
  PingResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("dummy_app.PingResult").msgclass
end
